# Object-oriented programming
Before introducing file inputs/outputs (I/O) and plotting, I would like to introduce a very important concept behind them, and also behind the Python language. It is called Object-Oriented Programming (OOP).

**Object** and **Class** are two important terms in this concept. An object is rather self-explanatory. It is a single "thing". Class is a "blueprint" of objects sharing the same **attributes** (characteristics they possess), and **methods** (actions they perform, similar to functions). An object can belong to multiple classes.

Let's illustrate the concept with examples.
Example 1:
- Object: A dog 
- Class: Dogs, that possesses common characteristics like hair, eye, hands, legs, etc. and performs actions in the same way, e.g. run, breathe, eat, etc.
- Class: Mammals

Example 2:
- Object: The number "2"
- Class: Integers
- Class: Real numbers
- Class: Numbers

Why do I mention this? Because Python is an object-oriented language. Everything in Python is an object! You can call `type()` to see the class.

Recall Part 1 where we introduced data types. Every number and string and boolean value is an object, belonging to their own class.

In [1]:
# Integer
print(type(1))
print(type(2+3))

# Float 
print(type(1.0))
print(type(5/2))
print(type(1e2))

# Complex
print(type(1.0+1.0j))

# String
print(type('Happy New Year!'))

# Boolean (True or False)
print(type(True))
print(type(1==2)) # More on logical operators later

# List
fruits = ['apple', 'orange', 'banana', 'grape', 'strawberry'] 
print(type(fruits))

# Dictionary
site_info = {'Name':'Hong Kong', 'lat':22.3, 'lon':114.2, 'Time zone':'UTC+8', 'Currency':'HKD'}
print(type(site_info))

# Function
def one():
    return 1

print(type(one))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>
<class 'bool'>
<class 'list'>
<class 'dict'>
<class 'function'>


_Note: The operators, e.g. +, -, *, /, etc. are how objects interact with each other. But I won't go into detail on this._

## Attributes and Methods
As mentioned above, objects in a class should share the same **attributes** (characteristics they possess), and **methods** (actions they perform, similar to functions). Let's take a look at how to see the attributes and use the methods.

**Syntax**: (to see the value of an attribute)
```
value = class.attribute
```
Note:
- By convention, people use **setter** and **getter methods** to set and get the values of attributes, i.e. object.set_*attribute*() and object.get_*attribute*(). Examples will be shown in [Part 5b: Advanced Plotting](./Part5b_Advanced_Plotting.ipynb).

**Syntax**: (to call a method)
```
class.method(arguments) 
```
Note that you need the brackets to call the method, just like a function.

### Example with strings

In [2]:
# Let's use a string as an example
word = "Hello"
# Print an attribute "__class__"
print(word.__class__)

<class 'str'>


For the commonly used classes, attributes are quite rarely used. But in libraries (modules) and plotting, you will see it more.

*Note: I think it is also a common practice that developers define a method to see a "private" attribute, rather than having a "public" attribute being seen directly (so that users cannot modify them easily).*

In [3]:
# Print the returned values after calling the methods "upper" and "lower"
print(word.upper())
print(word.lower())
# Here I intentionally omit the calling brackets (parentheses) to show what happens when accessing the method
print(word.upper)

HELLO
hello
<built-in method upper of str object at 0x10fdbe6c0>


*Note: To learn more about attributes and methods, you may want to take a look at this: [Accessing attributes in Python](http://blog.thedigitalcatonline.com/blog/2015/01/12/accessing-attributes-in-python/)*

We have used *string*.**format**(*argmuent*) before. Take another look at this function now. It is basically a method of class *string* that processes a formatted string given the input arguments.

In [4]:
sol1, sol2 = 2,3
print(sol1)
print(sol2)
# Use {} with indices starting from 0 to tell the function where to insert the input arguments
# Note that 0 refers to 1st input, 1 refers to 2nd input, so forth so on.
conclusion = 'The solutions are {0} and {1}'.format(sol1,sol2)
print(conclusion)

2
3
The solutions are 2 and 3


### Example with NumPy arrays


In [6]:
# import library
import numpy as np
z = np.arange(15).reshape(3, 5)
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### Attributes

In [10]:
# number of dimensions 
print(z.ndim) # => z is a 2D array
# length in each dimension 
print(z.shape) 

2
(3, 5)


#### Methods

In [11]:
# sum over all elements
print(z.sum()) 
# sum over the 1st axis (axis=0)
print(z.sum(axis=0))

105
[15 18 21 24 27]


In [12]:
# mean() works similarly
print(z.mean())
print(z.mean(axis=0))

7.0
[5. 6. 7. 8. 9.]


In [13]:
# change the way the elements are organized
print(z.reshape(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Modules
Modules (or Libraries) in Python is another useful class type. People use modules to write functions and statements for specific purposes, e.g. "*NumPy*" provides simplistic syntax and high performance array objects to deal with scientific computing, "*datetime*" deals with date and time easily, "*os*" allows user to use commands from the backend operating system within a running script, etc...

Next part we will learn plotting using a module called **matplotlib**. Later we will also introduce two modules used in atmospheric science studies. They are **xarray** and **Cartopy**.

Next part: [Plotting](./Part5_Plotting.ipynb)